@startmindmap Laborbericht-Vorlage-toc
* TOC
**[#Orange]  1 Einleitung 
**[#Orange]  2 Lösungsweg 
***[#lightblue]  2.1 Formel 
***[#lightblue]  2.2 Code 
**[#Orange]  3 Lösung 
**[#Orange]  4 Reflektion 
left side
**[#Orange]  5 Quellen 
**[#Orange]  6 Anhang 
**[#Orange]  7 Anpassung auf Basis des Feedbacks 
@endmindmap
